export const univData = [
	{ "nama": "Akademi Komunitas Negeri Pacitan", "namaProdi": [] },
	{
	  "nama": "Akademi Komunitas Negeri Putra Sang Fajar Blitar",
	  "namaProdi": []
	},
	{
	  "nama": "Institut Pertanian Bogor",
	  "namaProdi": [
		"Komunikasi Digital dan Media (D4)",
		"Agronomi dan Hortikultura (S1)",
		"Statistika (S1)",
		"Biologi (S1)",
		"Silvikultur (S1)",
		"Teknologi Hasil Hutan (S1)",
		"Teknik Pertanian dan Biosistem (S1)",
		"Ilmu Ekonomi Syariah (S1)",
		"Statistika dan Sains Data (S1)",
		"Arsitektur Lanskap (S1)",
		"Biokimia (S1)",
		"Kecerdasan Buatan (S1)",
		"Teknologi Produksi Ternak (S1)",
		"Ilmu Keluarga Dan Konsumen (S1)",
		"Ekowisata (D4)",
		"Sains Biomedis (S1)",
		"Teknologi Rekayasa Perangkat Lunak (D4)",
		"Bioinformatika (S1)",
		"Analisis Kimia (D4)",
		"Teknologi dan Manajemen Ternak (D4)",
		"Ekonomi Pembangunan (S1)",
		"Ekonomi Sumberdaya Dan Lingkungan (S1)",
		"Teknik Sipil dan Lingkungan (S1)",
		"Teknologi Dan Manajemen Perikanan Tangkap (S1)",
		"Teknologi dan Manajemen Produksi Perkebunan (D4)",
		"Manajemen (S1)",
		"Teknologi Industri Benih (D3)",
		"Ilmu Gizi (S1)",
		"Akuntansi (D4)",
		"Ilmu Komputer (S1)",
		"Fisika (S1)",
		"Matematika (S1)",
		"Proteksi Tanaman (S1)",
		"Teknik dan Manajemen Lingkungan (D4)",
		"Teknologi Dan Manajemen Perikanan Budidaya (S1)",
		"Paramedik Veteriner (D4)",
		"Komunikasi dan Pengembangan Masyarakat (S1)",
		"Konservasi Sumberdaya Hutan Dan Ekowisata (S1)",
		"Aktuaria (S1)",
		"Teknologi Hasil Perairan (S1)",
		"Manajemen Industri (D4)",
		"Teknologi Produksi dan Pengembangan Masyarakat Pertanian (D4)",
		"Teknologi Rekayasa Komputer (D4)",
		"Bisnis (S1)",
		"Kedokteran (S1)",
		"Teknik Industri Pertanian (S1)",
		"Teknologi Hasil Ternak (S1)",
		"Meteorologi Terapan (S1)",
		"Supervisor Jaminan Mutu Pangan (D4)",
		"Manajemen Sumberdaya Lahan (S1)",
		"Teknologi Industri Pertanian (S1)",
		"Teknologi dan Manajemen Pembenihan Ikan (D4)",
		"Nutrisi dan Teknologi Pakan (S1)",
		"Teknologi Pangan (S1)",
		"Kedokteran Hewan (S1)",
		"Agribisnis (S1)",
		"Manajemen Industri Jasa Makanan dan Gizi (D4)",
		"Manajemen Sumberdaya Perairan (S1)",
		"Smart Agriculture (S1)",
		"Ilmu Dan Teknologi Kelautan (S1)",
		"Kimia (S1)",
		"Manajemen Hutan (S1)",
		"Manajemen Agribisnis (D4)"
	  ]
	},
	{
	  "nama": "Institut Seni Budaya Indonesia Bandung",
	  "namaProdi": [
		"Seni Rupa Murni (S1)",
		"Tari Sunda (D4)",
		"Kriya Seni (D3)",
		"Seni Tari (S1)",
		"Kriya (S1)",
		"Tata Rias dan Busana (D4)",
		"Desain Komunikasi Visual (S1)",
		"Televisi Dan Film (D4)",
		"Angklung dan Musik Bambu (D4)",
		"Antropologi Budaya (S1)",
		"Desain Interior (S1)",
		"Seni Karawitan (S1)",
		"Seni Teater (S1)"
	  ]
	},
	{
	  "nama": "Institut Seni Indonesia Surakarta",
	  "namaProdi": [
		"Tari (S1)",
		"Televisi Dan Film (S1)",
		"Destinasi Pariwisata (D4)",
		"Desain Mode Batik (D4)",
		"Koreografi Inkuiri (S1)",
		"Batik (D4)",
		"Seni Teater (S1)",
		"Seni Rupa Murni (S1)",
		"Keris dan Senjata Tradisional (D4)",
		"Tata Kelola Seni (D4)",
		"Etnomusikologi (S1)",
		"Kriya (S1)",
		"Desain Komunikasi Visual (S1)",
		"Fotografi (S1)",
		"Desain Interior (S1)",
		"Seni Karawitan (S1)",
		"Seni Pedalangan (S1)",
		"Seni Tari (S1)",
		"Teater (S1)",
		"Arsitektur (S1)",
		"Desain Produk Industri (S1)",
		"Kriya Seni (S1)",
		"Film dan Televisi (S1)",
		"Seni Murni (S1)",
		"Senjata Tradisional Keris (D4)",
		"Animasi (D4)",
		"Seni Intermedia (S1)"
	  ]
	},
	{
	  "nama": "Institut Seni Indonesia Yogyakarta",
	  "namaProdi": [
		"Tari (S1)",
		"Penyajian Musik (D4)",
		"Desain Media (D4)",
		"Musik (S1)",
		"Konservasi Seni (S1)",
		"Televisi Dan Film (S1)",
		"Batik dan Fashion (D3)",
		"Animasi (D3)",
		"Produksi Film dan Televisi (D4)",
		"Desain Mode Kriya Batik (D4)",
		"Tata Kelola Seni (S1)",
		"Seni Teater (S1)",
		"Seni Rupa Murni (S1)",
		"Pendidikan Musik (S1)",
		"Etnomusikologi (S1)",
		"Kriya (S1)",
		"Desain Komunikasi Visual (S1)",
		"Fotografi (S1)",
		"Pendidikan Seni Pertunjukan (S1)",
		"Desain Interior (S1)",
		"Seni Karawitan (S1)",
		"Seni Pedalangan (S1)",
		"Seni Tari (S1)",
		"Desain Produk (S1)",
		"Teater (S1)",
		"Seni Drama Tari dan Musik (S1)",
		"Kriya Seni (S1)",
		"Film dan Televisi (S1)",
		"Teater Musikal (D4)",
		"Penciptaan Musik (S1)",
		"Seni Murni (S1)",
		"Seni Musik (S1)",
		"Animasi (D4)"
	  ]
	},
	{
	  "nama": "Institut Teknologi Bandung",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Teknik Telekomunikasi (S1)",
		"Biologi (S1)",
		"Teknik dan Pengelolaan Sumber Daya Air (S1)",
		"Teknik Material (S1)",
		"Teknik Geologi (S1)",
		"Teknik Mesin (S1)",
		"Rekayasa Hayati (S1)",
		"Farmasi Klinik Dan Komunitas (S1)",
		"Teknik Fisika (S1)",
		"Teknik Metalurgi (S1)",
		"Teknik Informatika (S1)",
		"Mikrobiologi (S1)",
		"Teknik Tenaga Listrik (S1)",
		"Manajemen (S1)",
		"Kriya (S1)",
		"Desain Komunikasi Visual (S1)",
		"Sistem dan Teknologi Informasi (S1)",
		"Teknik Kimia (S1)",
		"Teknik Elektro (S1)",
		"Teknik Perminyakan (S1)",
		"Desain Interior (S1)",
		"Teknik Bioenergi dan Kemurgi (S1)",
		"Matematika (S1)",
		"Manajemen Rekayasa (S1)",
		"Fisika (S1)",
		"Perencanaan Wilayah Dan Kota (S1)",
		"Rekayasa Kehutanan (S1)",
		"Seni Rupa (S1)",
		"Teknik Geofisika (S1)",
		"Teknik Industri (S1)",
		"Aktuaria (S1)",
		"Teknik Pertambangan (S1)",
		"Manajemen Rekayasa Industri (S1)",
		"Teknologi Pasca Panen (S1)",
		"Desain Produk (S1)",
		"Rekayasa Pertanian (S1)",
		"Arsitektur (S1)",
		"Teknik Geodesi Dan Geomatika (S1)",
		"Kriya (PSDKU Kota Cirebon) (S1)",
		"Oseanografi (S1)",
		"Astronomi (S1)",
		"Sains Dan Teknologi Farmasi (S1)",
		"Teknik Pangan (S1)",
		"Rekayasa Infrastruktur Lingkungan (S1)",
		"Teknik Biomedis (S1)",
		"Teknik Sipil (S1)",
		"Meteorologi (S1)",
		"Perencanaan Wilayah dan Kota (PSDKU Kota Cirebon) (S1)",
		"Teknik Kelautan (S1)",
		"Kimia (S1)",
		"Kewirausahaan (S1)",
		"Teknik Dirgantara (S1)"
	  ]
	},
	{
	  "nama": "Institut Teknologi Sepuluh Nopember",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Teknik Telekomunikasi (S1)",
		"Statistika (S1)",
		"Teknologi Rekayasa Konstruksi Bangunan Air (D4)",
		"Biologi (S1)",
		"Teknik Material (S1)",
		"Bioteknologi (S1)",
		"Manajemen Bisnis (S1)",
		"Teknik Lepas Pantai (S1)",
		"Sains Aktuaria (S1)",
		"Rekayasa Perangkat Lunak (S1)",
		"Sains Analitik dan Instrumentasi Kimia (S1)",
		"Teknik Mesin (S1)",
		"Teknik Perkapalan (S1)",
		"Teknik Transportasi Laut (S1)",
		"Teknologi Rekayasa Konversi Energi (D4)",
		"Teknik Fisika (S1)",
		"Teknik Informatika (S1)",
		"Desain Komunikasi Visual (S1)",
		"Teknologi Rekayasa Kimia Industri (D4)",
		"Teknik Kimia (S1)",
		"Teknik Elektro (S1)",
		"Sistem Informasi (S1)",
		"Inovasi Digital (S1)",
		"Bisnis Digital (S1)",
		"Desain Interior (S1)",
		"Sains Data (S1)",
		"Matematika (S1)",
		"Fisika (S1)",
		"Perencanaan Wilayah Dan Kota (S1)",
		"Studi Pembangunan (S1)",
		"Teknik Industri (S1)",
		"Teknologi Informasi (S1)",
		"Teknik Geofisika (S1)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Analitika Logistik Terapan (D4)",
		"Teknologi Kedokteran (S1)",
		"Kedokteran (S1)",
		"Desain Produk (S1)",
		"Arsitektur (S1)",
		"Statistika Bisnis (D4)",
		"Rekayasa Keselamatan Proses (S1)",
		"Teknik Sipil (D4)",
		"Sains Komunikasi (S1)",
		"Teknik Komputer (S1)",
		"Teknik Geomatika (S1)",
		"Teknik Biomedik (S1)",
		"Teknik Pangan (S1)",
		"Teknik Sipil (S1)",
		"Teknik Kelautan (S1)",
		"Teknologi Rekayasa Otomasi (D4)",
		"Teknologi Rekayasa Instrumentasi (D4)",
		"Kimia (S1)",
		"Rekayasa Kecerdasan Artifisial (S1)",
		"Teknik Sistem Perkapalan (S1)"
	  ]
	},
	{
	  "nama": "Politeknik Elektronika Negeri Surabaya",
	  "namaProdi": [
		"Teknik Informatika (Kampus Kab Sumenep) (D3)",
		"Teknik Informatika (D4)",
		"Teknologi Game (D4)",
		"Teknologi Multimedia Broadcasting (Kampus Kab. Sumenep) (D3)",
		"PJJ Teknik Informatika (D3)",
		"Teknologi Rekayasa Multimedia (D4)",
		"Teknologi Multimedia Broadcasting (Kampus Kab Lamongan) (D3)",
		"Sistem Pembangkit Energi (D4)",
		"Teknik Informatika (D3)",
		"Teknik Telekomunikasi (D4)",
		"Teknik Elektronika (D3)",
		"Teknologi Multimedia dan Broadcasting (D3)",
		"Teknik Elektronika (D4)",
		"Teknik Telekomunikasi (D3)",
		"Teknik Komputer (D4)",
		"Teknik Elektro Industri (D3)",
		"Sains Data Terapan (D4)",
		"Teknik Elektro Industri (D4)",
		"Teknologi Rekayasa Internet (D4)",
		"Teknik Informatika (Kampus Kab Lamongan) (D3)",
		"PJJ Teknik Telekomunikasi (D4)",
		"Teknik Mekatronika (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Manufaktur Bandung",
	  "namaProdi": [
		"Teknologi Rekayasa Informatika Industri (D4)",
		"Teknologi Pengecoran Logam (D3)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Teknologi Rekayasa Perancangan Manufaktur (D4)",
		"Teknologi Perancangan Mekanik (D3)",
		"Pemeliharaan Mesin (D3)",
		"Teknologi Manufaktur (D3)",
		"Teknologi Rekayasa Mekatronika (D4)",
		"Teknologi Rekayasa Otomasi (D4)",
		"Rekayasa Perancangan Mekanik (D4)",
		"Teknologi Perancangan Perkakas Presisi (D3)",
		"Teknologi Rekayasa Sistem Aerial Nirawak (D4)",
		"Manajemen Teknologi Rekayasa (D4)",
		"Teknologi Rekayasa Material Maju (D4)",
		"Teknologi Pembuatan Perkakas Presisi (D3)",
		"Mekatronika (D3)"
	  ]
	},
	{
	  "nama": "Politeknik Maritim Negeri Indonesia",
	  "namaProdi": [
		"Nautika (D4)",
		"Teknologi Rekayasa Mekatronika (D4)",
		"teknika (D3)",
		"Nautika (D3)",
		"Teknologi Rekayasa Permesinan Kapal (D4)",
		"Ketatalaksanaan Pelayaran Niaga Dan Kepelabuhan (D3)",
		"Bisnis Dan Logistik Maritim (D4)",
		"Transportasi Laut (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Bandung",
	  "namaProdi": [
		"Teknik Informatika (D4)",
		"Bahasa Inggris (D3)",
		"Manajemen Aset (D4)",
		"Teknik Konstruksi Gedung (D3)",
		"Teknik Perancangan dan Konstruksi Mesin (D4)",
		"Teknik Pendingin Dan Tata Udara (D3)",
		"Destinasi Pariwisata (D4)",
		"Teknik Informatika (D3)",
		"Teknik Listrik (D3)",
		"Teknik Konservasi Energi (D4)",
		"Teknik Telekomunikasi (D4)",
		"Teknik Otomasi Industri (D4)",
		"Teknologi Pembangkit Tenaga Listrik (D4)",
		"Teknik Perawatan Dan Perbaikan Gedung (D4)",
		"Teknik Elektronika (D3)",
		"Teknik Kimia (D3)",
		"Akuntansi (D3)",
		"Keuangan Syariah (D4)",
		"Teknik Kimia Produksi Bersih (D4)",
		"Akuntansi Manajemen Pemerintahan (D4)",
		"Teknik Mesin (D3)",
		"Manajemen Pemasaran (D3)",
		"Akuntansi (D4)",
		"Administrasi Bisnis (D4)",
		"Manajemen Pemasaran (D4)",
		"Teknik Elektronika (D4)",
		"Teknik Konversi Energi (D3)",
		"Teknik Aeronautika (D3)",
		"Teknik Telekomunikasi (D3)",
		"Analis Kimia (D3)",
		"Teknik Pendingin dan Tata Udara (D4)",
		"Proses Manufaktur (D4)",
		"Administrasi Bisnis (D3)",
		"Teknik Konstruksi Sipil (D3)",
		"Teknik Perancangan Jalan Dan Jembatan (D4)",
		"Keuangan Dan Perbankan (D3)",
		"Usaha Perjalanan Wisata (D3)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Banyuwangi",
	  "namaProdi": [
		"Agribisnis (D4)",
		"Manajemen Konstruksi (D4)",
		"Teknik Manufaktur Kapal (D4)",
		"Teknologi Produksi Ternak (D4)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Teknologi Rekayasa Komputer (D4)",
		"Manajemen Bisnis Pariwisata (D4)",
		"Teknologi Budi Daya Perikanan/Teknologi Akuakultur (D4)",
		"Destinasi Pariwisata (D4)",
		"Pengembangan Produk Agroindustri (D4)",
		"Teknik Sipil (D3)",
		"Teknologi Rekayasa Kontruksi Jalan Dan Jembatan (D4)",
		"Teknologi Rekayasa Konstruksi Bangunan Gedung (D4)",
		"Pengelolaan Perhotelan (D4)",
		"Teknologi Produksi Tanaman Pangan (D4)",
		"Teknologi Rekayasa Perangkat Lunak (D4)",
		"Teknologi Pengolahan Hasil Ternak (D4)",
		"Bisnis Digital (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Cilacap",
	  "namaProdi": [
		"Teknologi Rekayasa Energi Terbarukan (D4)",
		"Teknologi Rekayasa Mekatronika (D4)",
		"Teknik Elektronika (D3)",
		"Teknik Mesin (D3)",
		"Teknologi Rekayasa Multimedia (D4)",
		"Pengembangan Produk Agroindustri (D4)",
		"Teknik Pengendalian Pencemaran Lingkungan (D4)",
		"Teknik Informatika (D3)",
		"Teknik Listrik (D3)",
		"Akuntansi Lembaga Keuangan Syariah (D4)",
		"Rekayasa Keamanan Siber (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Indramayu",
	  "namaProdi": [
		"Keperawatan (D3)",
		"Rekayasa Perangkat Lunak (D4)",
		"Teknik Pendingin dan Tata Udara (D3)",
		"Teknologi Rekayasa Instrumentasi dan Kontrol (D4)",
		"Teknik Mesin (D3)",
		"Sistem Informasi Kota Cerdas (D4)",
		"Teknik Informatika (D3)",
		"Perancangan Manufaktur (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Jakarta",
	  "namaProdi": [
		"Teknik Multimedia Digital (D4)",
		"Teknik Informatika (D4)",
		"Teknik Grafika (D3)",
		"Teknologi Rekayasa Konversi Energi (D4)",
		"Keuangan Dan Perbankan Syari ah (D4)",
		"Konstruksi Gedung (D3)",
		"Teknik Listrik (D3)",
		"Desain Grafis (D4)",
		"Teknik KontrukSi Gedung (D4)",
		"Teknologi Industri Cetak kemasan (D4)",
		"Konstruksi Sipil (D3)",
		"Akuntansi (D3)",
		"Teknik Mesin (D3)",
		"Elektronika Industri (D3)",
		"Teknik Otomasi Listrik Industri (D4)",
		"Teknologi Rekayasa Pembangkit Energi (D4)",
		"Manufaktur (D4)",
		"Manajemen Pemasaran Untuk Warga Negara Berkebutuhan Khusus (D3)",
		"Instrumentasi Dan Kontrol Industri (D4)",
		"Teknik Konversi Energi (D3)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Telekomunikasi (D3)",
		"Pembangkit Tenaga Listrik (D4)",
		"Teknik Multimedia dan Jaringan (D4)",
		"Penerbitan (D3)",
		"Teknik Mesin (Kampus Kab. Demak) (D3)",
		"Administrasi Bisnis (D3)",
		"BroadBand Multimedia (D4)",
		"Teknologi Rekayasa Cetak Dan Grafis 3 Dimensi (D4)",
		"Akuntansi Keuangan (D4)",
		"Teknik Perancangan Jalan Dan Jembatan (D4)",
		"Keuangan dan Perbankan (D4)",
		"Teknologi Rekayasa Pemeliharaan Alat Berat (D4)",
		"Manufaktur (Kampus Kota Pekalongan) (D4)",
		"Teknologi Rekayasa Manufaktur (Kampus Kota Pekalongan) (D4)",
		"Administrasi Bisnis Terapan (D4)",
		"Manajemen Keuangan (D4)",
		"Alat Berat (D3)",
		"Bahasa Inggris untuk Komunikasi Bisnis dan Profesional (D4)",
		"Usaha Jasa Konvensi, Perjalanan Insentif, dan Pameran (Kampus Kab. Demak) (D4)",
		"Keuangan Dan Perbankan (D3)",
		"Usaha Jasa Konvensi, Perjalanan Insentif dan Pameran (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Jember",
	  "namaProdi": [
		"Manajemen Agribisnis (D3)",
		"Teknik Informatika (D4)",
		"Teknologi Industri Pangan (D3)",
		"Bahasa Inggris (D3)",
		"Produksi Media (D4)",
		"Budidaya Tanaman Perkebunan (D4)",
		"Manajemen Informatika (D3)",
		"Produksi Tanaman Hortikultura (D3)",
		"Destinasi Pariwisata (D4)",
		"Teknik Informatika (Kampus Kab Nganjuk) (D4)",
		"Produksi Tanaman Perkebunan (D3)",
		"Rekam Medik (D4)",
		"Mesin Otomotif (D4)",
		"Pengelolaan Perkebunan Kopi (D4)",
		"Teknik Komputer (D3)",
		"Produksi Ternak (D3)",
		"Manajemen Agroindustri (Kampus Kab Sidoarjo) (D4)",
		"Manajemen Informasi Kesehatan (Kampus Kab. Ngawi) (D4)",
		"Teknik Energi Terbarukan (D4)",
		"Teknologi Rekayasa Komputer (D4)",
		"Manajemen Bisnis Unggas (D4)",
		"Teknik Produksi Benih (D4)",
		"Teknologi Rekayasa Pangan (D4)",
		"Manajemen Agribisnis (Kampus. Kab Ngawi) (D4)",
		"Manajemen Pemasaran Internasional (D4)",
		"Manajemen Agribisnis (Kampus Kab. Nganjuk) (D3)",
		"Manajemen Agroindustri (D4)",
		"Bisnis Digital (D4)",
		"Promosi Kesehatan (D4)",
		"Teknik Informatika (Kampus Kab. Sidoarjo) (D4)",
		"Teknologi Rekayasa Perangkat Lunak (Kampus Kabupaten Sabu Raijua) (D4)",
		"Gizi Klinik (D4)",
		"Teknologi Rekayasa Mekatronika (D4)",
		"Akuntansi Sektor Publik (D4)",
		"Manajemen Informasi Kesehatan (D4)",
		"Keteknikan Pertanian (D3)",
		"Teknologi Pakan Ternak (D4)",
		"Teknologi Produksi Tanaman Pangan (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Madiun",
	  "namaProdi": [
		"Pemasaran Digital (D4)",
		"Perkeretaapian (D4)",
		"Teknologi Rekayasa Otomotif (D4)",
		"Bahasa Inggris (D3)",
		"Teknologi Rekayasa Elektronika (D4)",
		"Akuntansi Sektor Publik (D4)",
		"Teknik Komputer Kontrol (D3)",
		"Teknik Listrik (D3)",
		"Akuntansi (D3)",
		"Teknologi Informasi (D3)",
		"Bahasa Inggris Untuk Komunikasi Bisnis Dan Profesional (D4)",
		"Teknologi Rekayasa Otomasi (D4)",
		"Akuntansi Perpajakan (D4)",
		"Teknologi Rekayasa Perangkat Lunak (D4)",
		"Administrasi Bisnis (D3)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Madura",
	  "namaProdi": [
		"Teknik Mesin Alat Berat (D3)",
		"Teknik Bangunan Kapal (D3)",
		"Teknik Listrik Industri (D3)",
		"Teknologi Rekayasa Keselamatan (D4)",
		"Teknologi Rekayasa Otomasi (D4)",
		"Keperawatan (D3)",
		"Promosi Kesehatan (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Malang",
	  "namaProdi": [
		"Usaha Perjalanan Wisata (D4)",
		"Teknik Informatika (D4)",
		"Teknik Mesin (Kampus Kota Kediri) (D3)",
		"Akuntansi Manajemen (D4)",
		"Teknologi Pemeliharaan Pesawat Udara (D3)",
		"Jaringan Telekomunikasi Digital (D4)",
		"Keuangan (Kampus Kota Kediri) (D4)",
		"Teknik Mesin Produksi dan Perawatan (Kampus Kota Kediri) (D4)",
		"Manajemen Informatika (Kampus Kab.Pamekasan) (D3)",
		"Teknik Sipil (D3)",
		"Teknologi Informasi (Kampus Kab Lumajang) (D3)",
		"Bahasa Inggris Untuk Industri Pariwisata (D4)",
		"Teknologi Konstruksi Jalan, Jembatan, dan Bangunan Air (D3)",
		"Teknologi Rekayasa Konstruksi Jalan Dan Jembatan (D4)",
		"Teknik Listrik (D3)",
		"Teknik Otomotif Elektronik (D4)",
		"Bahasa Inggris untuk Komunikasi Bisnis dan Profesional (D4)",
		"Teknologi Pertambangan (D3)",
		"Teknik Elektronika (D3)",
		"Teknologi Kimia Industri (D4)",
		"Teknik Kimia (D3)",
		"Akuntansi (D3)",
		"Teknik Mesin (D3)",
		"Manajemen Pemasaran (D4)",
		"Teknik Elektronika (D4)",
		"Sistem Informasi Bisnis (D4)",
		"Teknik Elektronika (Kampus Kab. Kediri) (D4)",
		"Teknik Telekomunikasi (D3)",
		"Teknik Mesin Produksi dan Perawatan (D4)",
		"Akuntansi (Kampus Kota Kediri) (D3)",
		"Akuntansi Manajemen (Kampus Kab Pamekasan) (D4)",
		"Akuntansi (Kampus Kab. Lumajang) (D3)",
		"Administrasi Bisnis (D3)",
		"Teknik Otomotif Elektronik (Kampus Kab. Pamekasan) (D4)",
		"Teknologi Rekayasa Otomotif (Kampus Kab. Lumajang) (D4)",
		"Teknologi Sipil (Kampus Kab Lumajang) (D3)",
		"Manajemen Rekayasa Konstruksi (D4)",
		"Pengelolaan Arsip dan Rekaman Informasi (D4)",
		"Keuangan (D4)",
		"Sistem Kelistrikan (D4)",
		"Manajemen Informatika (Kampus Kota Kediri) (D3)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Media Kreatif",
	  "namaProdi": [
		"Teknologi Permainan (D4)",
		"Desain Grafis (D3)",
		"Teknik Grafika (D3)",
		"Produksi Film dan Televisi (D4)",
		"Teknologi Rekayasa Multimedia (D4)",
		"Desain Mode (D4)",
		"Penerbitan (Kampus Kota Medan) (D3)",
		"Teknik Kemasan (D3)",
		"Penerbitan (Kampus Kota Makassar) (D3)",
		"Periklanan (Kampus Kota Makassar) (D3)",
		"Desain Grafis (Kampus Kota Makassar) (D3)",
		"Periklanan (D3)",
		"Penerbitan (D3)",
		"Periklanan (Kampus Kota Medan) (D3)",
		"Teknik Grafika (Kampus Kota Makassar) (D3)",
		"Penyiaran (D3)",
		"Desain Grafis (Kampus Kota Medan) (D3)",
		"Pemeliharaan Mesin (D3)",
		"Fotografi (D3)",
		"Seni Kuliner (D3)",
		"Teknik Grafika (Kampus Kota Medan) (D3)",
		"Teknologi Rekayasa Pengemasan (D4)",
		"Pengelolaan Perhotelan (D4)",
		"Animasi (D4)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Semarang",
	  "namaProdi": [
		"Komputerisasi Akuntansi (D4)",
		"Konstruksi Gedung (D3)",
		"Manajemen Pemasaran/Marketing (D3)",
		"Teknik Informatika (D3)",
		"Teknik Listrik (D3)",
		"Perbankan Syari ah (D4)",
		"Teknik Telekomunikasi (D4)",
		"Teknik Perawatan Dan Perbaikan Gedung (D4)",
		"Konstruksi Sipil (D3)",
		"Perancangan Jalan dan Jembatan (D4)",
		"Teknik Elektronika (D3)",
		"Akuntansi (D3)",
		"Akuntansi Manajerial (D4)",
		"Analis Keuangan (D4)",
		"Teknik Mesin (D3)",
		"Teknologi Rekayasa Pembangkit Energi (D4)",
		"Teknik Konversi Energi (D3)",
		"Teknologi Rekayasa Komputer (D4)",
		"Teknologi Rekayasa Elektronika (D4)",
		"Teknik Telekomunikasi (D3)",
		"Teknik Mesin Produksi dan Perawatan (D4)",
		"Administrasi Bisnis (D3)",
		"Manajemen Bisnis Internasional (D4)",
		"Teknologi Rekayasa Instalasi Listrik (D4)",
		"Administrasi Bisnis Terapan (D4)",
		"Keuangan Dan Perbankan (D3)"
	  ]
	},
	{
	  "nama": "Politeknik Negeri Subang",
	  "namaProdi": [
		"Teknologi Rekayasa Manufaktur (D4)",
		"Pemeliharaan Mesin (D3)",
		"Agroindustri (D3)",
		"Teknologi Produksi Tanaman Pangan (D4)",
		"Teknologi Rekayasa Perangkat Lunak (D4)",
		"Keperawatan (D3)",
		"Sistem Informasi (D3)"
	  ]
	},
	{
	  "nama": "Politeknik Perkapalan Negeri Surabaya",
	  "namaProdi": [
		"Manajemen Bisnis (D4)",
		"Teknik Kelistrikan Kapal (D3)",
		"Teknik Permesinan Kapal (D3)",
		"Teknologi Rekayasa Konstruksi Perkapalan (D4)",
		"Teknik Bangunan Kapal (D3)",
		"Teknik Keselamatan Dan Kesehatan Kerja (D4)",
		"Teknik Desain Dan Manufaktur (D4)",
		"Teknik Perpipaan (D4)",
		"Teknik Pengolahan Limbah (D4)",
		"Teknik Perancangan Dan Konstruksi Kapal (D4)",
		"Teknik Permesinan Kapal (D4)",
		"Teknologi Rekayasa Energi Berkelanjutan (D4)",
		"Teknik Otomasi (D4)",
		"Teknik Pengelasan (D4)",
		"Teknik Perancangan Dan Konstruksi Kapal (D3)",
		"Teknik Kelistrikan Kapal (D4)"
	  ]
	},
	{
	  "nama": "Universitas Airlangga",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Manajemen Perkantoran Digital (D4)",
		"Statistika (S1)",
		"Ilmu Hubungan Internasional (S1)",
		"Biologi (S1)",
		"Teknik Informatika (D4)",
		"Teknologi Veteriner (D4)",
		"Bahasa Inggris (D3)",
		"Kesehatan Masyarakat SIKIA Banyuwangi (S1)",
		"Antropologi (S1)",
		"Destinasi Pariwisata (D4)",
		"Kedokteran Gigi (S1)",
		"Teknologi Sains Data (S1)",
		"Ilmu Sejarah (S1)",
		"Akuntansi (S1)",
		"Akuakultur K. Banyuwangi (S1)",
		"Bahasa dan Sastra Indonesia (S1)",
		"Ekonomi Pembangunan (S1)",
		"Ilmu Informasi dan Perpustakaan (S1)",
		"Keselamatan dan Kesehatan Kerja (D4)",
		"Teknologi Rekayasa Instrumentasi dan Kontrol (D4)",
		"Kesehatan Masyarakat K. Banyuwangi (S1)",
		"Kedokteran Hewan SIKIA Banyuwangi (S1)",
		"Administrasi Publik (S1)",
		"Kesehatan Masyarakat (S1)",
		"Ilmu Politik (S1)",
		"Kedokteran Hewan K. Banyuwangi (S1)",
		"Manajemen (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Teknologi Laboratorium Medik (D4)",
		"Keperawatan (S1)",
		"Sistem Informasi (S1)",
		"Manajemen Pemasaran (D3)",
		"Farmasi (S1)",
		"Teknik Elektro (S1)",
		"Teknik Robotika dan Kecerdasan Buatan (S1)",
		"Akuakultur Fakultas Ilmu Kesehatan, Kedokteran, dan Ilmu Alam Banyuwangi (S1)",
		"Teknik Gigi (D3)",
		"Fisioterapi (D4)",
		"Teknologi Hasil Perikanan (S1)",
		"Fisika (S1)",
		"Matematika (S1)",
		"Teknik Industri (S1)",
		"Ilmu Komunikasi (S1)",
		"Manajemen Perhotelan (D4)",
		"Kedokteran (S1)",
		"Paramedik Veteriner (D3)",
		"Pengobat Tradisional (D4)",
		"Sosiologi (S1)",
		"Kedokteran Hewan Fakultas Ilmu Kesehatan, Kedokteran, dan Ilmu Alam Banyuwangi (S1)",
		"Teknologi Laboratorium Medis (D3)",
		"Bahasa dan Sastra Inggris (S1)",
		"Kesehatan Masyarakat Fakultas Ilmu Kesehatan, Kedokteran, dan Ilmu Alam Banyuwangi (S1)",
		"Teknologi Kesehatan Gigi (D4)",
		"Akuakultur SIKIA Banyuwangi (S1)",
		"Kedokteran Hewan (S1)",
		"Kearsipan Dan Informasi Digital (D4)",
		"Perpajakan (D3)",
		"Teknik Biomedis (S1)",
		"Teknologi Radiologi Pencitraan (D4)",
		"Gizi (S1)",
		"Studi Kejepangan (S1)",
		"Kedokteran Fakultas Ilmu Kesehatan, Kedokteran, dan Ilmu Alam Banyuwangi (S1)",
		"Perpustakaan (D3)",
		"Perbankan dan Keuangan (D4)",
		"Psikologi (S1)",
		"Kebidanan (S1)",
		"Ekonomi Islam (S1)",
		"Kimia (S1)",
		"Rekayasa Nanoteknologi (S1)",
		"Keselamatan Kesehatan Kerja (D3)",
		"Bahasa dan Sastra Jepang (S1)",
		"Akuakultur (S1)",
		"Keperawatan (D3)"
	  ]
	},
	{
	  "nama": "Universitas Brawijaya",
	  "namaProdi": [
		"Teknik Pertanian (S1)",
		"Biologi (S1)",
		"Peternakan (S1)",
		"Pendidikan Dokter Gigi (S1)",
		"Akuntansi (S1)",
		"Pendidikan Dokter Hewan (S1)",
		"Desain Grafis (D4)",
		"Agroekoteknologi (S1)",
		"Administrasi Publik (S1)",
		"Ilmu Hukum (S1)",
		"Teknik Elektro (S1)",
		"Administrasi Bisnis (S1)",
		"Teknologi Hasil Perikanan (S1)",
		"Industri Peternakan Cerdas (S1)",
		"Teknik Pengairan (S1)",
		"Perencanaan Wilayah Dan Kota (S1)",
		"Ilmu Komunikasi (S1)",
		"Ekonomi, Keuangan dan Perbankan (S1)",
		"Teknik Komputer (S1)",
		"Kimia (S1)",
		"Manajemen Sumber Daya Perairan (S1)",
		"Bioteknologi (S1)",
		"Antropologi (S1)",
		"Ekonomi Pembangunan (S1)",
		"Pariwisata (S1)",
		"Keuangan dan Perbankan (D3)",
		"Manajemen (S1)",
		"Agribisnis (Kampus Kota Kediri) (S1)",
		"Farmasi (S1)",
		"Sains Data (S1)",
		"Matematika (S1)",
		"Peternakan (Kampus kota Kediri) (S1)",
		"Teknik Industri (S1)",
		"Agrobisnis Perikanan (S1)",
		"Manajemen Perhotelan (D4)",
		"Ilmu Keperawatan (S1)",
		"Akuakultur (Kampus Kota Kediri) (S1)",
		"Pendidikan Teknologi Informasi (S1)",
		"Teknologi Industri Pertanian (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Agribisnis (S1)",
		"Agroekoteknologi (Kampus Kota Kediri) (S1)",
		"Teknik Lingkungan (S1)",
		"Statistika (S1)",
		"Teknik Mesin (S1)",
		"Administrasi Pendidikan (S1)",
		"Kehutanan (S1)",
		"Bioinformatika (S1)",
		"Instrumentasi (S1)",
		"Teknik Bioproses (S1)",
		"Pendidikan Bahasa Jepang (S1)",
		"Ilmu Gizi (S1)",
		"Ilmu Politik (S1)",
		"Sistem Informasi (S1)",
		"Fisika (S1)",
		"Teknik Geofisika (S1)",
		"Bahasa dan Sastra Prancis (S1)",
		"Kedokteran (S1)",
		"Teknologi Informasi (D3)",
		"Sastra Cina (S1)",
		"Pemanfaatan Sumber Daya Perikanan (S1)",
		"Hubungan Internasional (S1)",
		"Sosial Ekonomi Perikanan (Kampus Kota Kediri) (S1)",
		"Budidaya Perairan (S1)",
		"Perpajakan (S1)",
		"Teknologi Bioproses (S1)",
		"Sastra Jepang (S1)",
		"Kewirausahaan (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Ilmu Pemerintahan (S1)",
		"Teknik Informatika (S1)",
		"Seni Rupa Murni (S1)",
		"Teknik Kimia (S1)",
		"Teknologi Informasi (S1)",
		"Arsitektur (S1)",
		"Sosiologi (S1)",
		"Ilmu Aktuaria (S1)",
		"Sastra Inggris (S1)",
		"Administrasi Bisnis (D3)",
		"Teknik Sipil (S1)",
		"Psikologi (S1)",
		"Ilmu Perpustakaan (S1)",
		"Kebidanan (S1)",
		"Ekonomi Islam (S1)",
		"Ilmu Kelautan (S1)",
		"Ilmu dan Teknologi Pangan (S1)"
	  ]
	},
	{
	  "nama": "Universitas Diponegoro",
	  "namaProdi": [
		"Biologi (S1)",
		"Manajemen (D3)",
		"Informatika (S1)",
		"Peternakan (S1)",
		"Akuntansi Perpajakan (D4)",
		"Akuntansi (S1)",
		"Agroekoteknologi (S1)",
		"Administrasi Publik (S1)",
		"Teknologi Rekayasa Kimia Industri (D4)",
		"Akuntansi (D3)",
		"Teknik Elektro (S1)",
		"Keselamatan dan Kesehatan Kerja (S1)",
		"Administrasi Bisnis (S1)",
		"Bisnis Digital (S1)",
		"Teknologi Hasil Perikanan (S1)",
		"Perencanaan Wilayah Dan Kota (S1)",
		"Ilmu Komunikasi (S1)",
		"Administrasi Perpajakan K. Batang (D3)",
		"Administrasi Publik (Kampus Kab Rembang) (S1)",
		"Ilmu Perpustakaan dan Informasi (S1)",
		"Rekayasa Perancangan Mekanik (D4)",
		"Teknik Komputer (S1)",
		"Hubungan Masyarakat K. Batang (D3)",
		"Kimia (S1)",
		"Manajemen Sumber Daya Perairan (S1)",
		"Bioteknologi (S1)",
		"Teknologi dan Bisnis Perikanan dan Kelautan (S1)",
		"Teknik Infrastruktur Sipil dan Perancangan Arsitektur (D4)",
		"Manajemen (S1)",
		"Kesehatan Masyarakat (S1)",
		"Farmasi (S1)",
		"Matematika (S1)",
		"Agribisnis Kampus Batang (S1)",
		"Teknik Industri (S1)",
		"Teknik Listrik Industri (D4)",
		"Teknologi Pangan (S1)",
		"Bahasa Asing Terapan (D4)",
		"Agribisnis (S1)",
		"Teknologi Rekayasa Otomasi (D4)",
		"Manajemen Kampus Kab Rembang (D3)",
		"Manajemen K. Rembang (D3)",
		"Teknik Lingkungan (S1)",
		"Statistika (S1)",
		"Teknik Mesin (S1)",
		"Teknik Perkapalan (S1)",
		"Administrasi Pajak (D3)",
		"Kedokteran Gigi (S1)",
		"Perencanaan Tata Ruang Wilayah dan Kota K. Pekalongan (D3)",
		"Hukum (S1)",
		"Antropologi Sosial (S1)",
		"Informasi dan Humas (D4)",
		"Fisika (S1)",
		"Perencanaan Tata Ruang Wilayah Dan Kota (D3)",
		"Hubungan Masyarakat (D3)",
		"Kedokteran (S1)",
		"Administrasi Pajak K. Batang (D3)",
		"Oseanografi (S1)",
		"Ekonomi (S1)",
		"Hubungan Internasional (S1)",
		"Teknologi Rekayasa Konstruksi Perkapalan (D4)",
		"Akuakultur (S1)",
		"Manajemen dan Administrasi Logistik (D4)",
		"Bahasa dan Kebudayaan Jepang (S1)",
		"Teknik Geologi (S1)",
		"Ilmu Pemerintahan (S1)",
		"Teknik Kimia (S1)",
		"Keperawatan (S1)",
		"Sejarah (S1)",
		"Arsitektur (S1)",
		"Perencanaan Tata Ruang dan Pertanahan (D4)",
		"Sastra Inggris (S1)",
		"Teknik Geodesi (S1)",
		"Sastra Indonesia (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Psikologi (S1)",
		"Ilmu Perpustakaan (S1)",
		"Ekonomi Islam (S1)",
		"Akuntansi K. Pekalongan (D3)",
		"Ilmu Kelautan (S1)",
		"Perikanan Tangkap (S1)"
	  ]
	},
	{
	  "nama": "Universitas Gadjah Mada",
	  "namaProdi": [
		"Gizi Kesehatan (S1)",
		"Teknik Pertanian (S1)",
		"Biologi (S1)",
		"Pengelolaan Hutan (D4)",
		"Teknologi Survei dan Pemetaan Dasar (D4)",
		"Akuntansi (S1)",
		"Arkeologi (S1)",
		"Mikrobiologi Pertanian (S1)",
		"Teknik Pengelolaan dan Perawatan Alat Berat (D4)",
		"Perencanaan Wilayah dan Kota (S1)",
		"Teknik Elektro (S1)",
		"Agronomi (S1)",
		"Teknologi Hasil Perikanan (S1)",
		"Sistem Informasi Geografis (D4)",
		"Ilmu Komunikasi (S1)",
		"Pembangunan Wilayah (S1)",
		"Manajemen dan Kebijakan Publik (S1)",
		"Bahasa, Sastra, dan Budaya Jawa (S1)",
		"Teknologi Rekayasa Mesin (D4)",
		"Kedokteran Hewan (S1)",
		"Kartografi dan Penginderaan Jauh (S1)",
		"Kimia (S1)",
		"Teknik Sumber Daya Air (S1)",
		"Bahasa dan Kebudayaan Korea (S1)",
		"Teknologi Veteriner (D4)",
		"Filsafat (S1)",
		"Teknologi Pangan dan Hasil Pertanian (S1)",
		"Politik dan Pemerintahan (S1)",
		"Ekonomi Pertanian dan Agribisnis (S1)",
		"Teknik Infrastruktur Lingkungan (S1)",
		"Bahasa dan Sastra Indonesia (S1)",
		"Pariwisata (S1)",
		"Teknik Nuklir (S1)",
		"Bisnis Perjalanan Wisata (D4)",
		"Manajemen (S1)",
		"Farmasi (S1)",
		"Pembangunan Ekonomi Kewilayahan (D4)",
		"Ilmu Komputer (S1)",
		"Matematika (S1)",
		"Teknik Industri (S1)",
		"Pembangunan Sosial dan Kesejahteraan (S1)",
		"Sastra Jawa (S1)",
		"Ilmu Keperawatan (S1)",
		"Penyuluhan dan Komunikasi Pertanian (S1)",
		"Teknologi Industri Pertanian (S1)",
		"Akuntansi Sektor Publik (D4)",
		"Manajemen dan Penilaian Properti (D4)",
		"Manajemen Informasi Kesehatan (D4)",
		"Statistika (S1)",
		"Ilmu Hubungan Internasional (S1)",
		"Teknik Mesin (S1)",
		"Kedokteran Gigi (S1)",
		"Geofisika (S1)",
		"Teknik Fisika (S1)",
		"Kehutanan (S1)",
		"Teknologi Rekayasa Perangkat Lunak (D4)",
		"Ilmu Tanah (S1)",
		"Hukum (S1)",
		"Higiene Gigi (S1)",
		"Bahasa Jepang untuk Komunikasi Bisnis dan Profesional (D4)",
		"Pengembangan Produk Agroindustri (D4)",
		"Teknik Pengelolaan dan Pemeliharaan Infrastruktur Sipil (D4)",
		"Fisika (S1)",
		"Proteksi Tanaman (S1)",
		"Sastra Prancis (S1)",
		"Perbankan (D4)",
		"Bahasa dan Sastra Prancis (S1)",
		"Kedokteran (S1)",
		"Bahasa Inggris (D4)",
		"Sastra Jepang (S1)",
		"Akuakultur (S1)",
		"Teknologi Rekayasa Elektro (D4)",
		"Bahasa dan Kebudayaan Jepang (S1)",
		"Teknik Geologi (S1)",
		"Teknologi Rekayasa Instrumentasi dan Kontrol (D4)",
		"Teknologi Rekayasa Pelaksanaan Bangunan Sipil (D4)",
		"Teknik Kimia (S1)",
		"Ilmu dan Industri Peternakan (S1)",
		"Teknologi Informasi (S1)",
		"Ilmu Ekonomi (S1)",
		"Sastra Arab (S1)",
		"Sejarah (S1)",
		"Arsitektur (S1)",
		"Sosiologi (S1)",
		"Ilmu Aktuaria (S1)",
		"Elektronika dan Instrumentasi (S1)",
		"Sastra Inggris (S1)",
		"Teknik Geodesi (S1)",
		"Teknologi Rekayasa Internet (D4)",
		"Teknik Biomedis (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Geografi Lingkungan (S1)",
		"Pengelolaan Arsip dan Rekaman Informasi (D4)",
		"Psikologi (S1)",
		"Manajemen Sumberdaya Akuatik (S1)",
		"Antropologi Budaya (S1)"
	  ]
	},
	{
	  "nama": "Universitas Indonesia",
	  "namaProdi": [
		"Biologi (S1)",
		"Sastra Daerah untuk Sastra Jawa (S1)",
		"Ilmu Kesejahteraan Sosial (S1)",
		"Pendidikan Dokter Gigi (S1)",
		"Akuntansi (S1)",
		"Arkeologi (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Teknik Elektro (S1)",
		"Keselamatan dan Kesehatan Kerja (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Filsafat (S1)",
		"Administrasi Keuangan Dan Perbankan (D3)",
		"Teknik Komputer (S1)",
		"Geografi (S1)",
		"Terapi Okupasi (D4)",
		"Kimia (S1)",
		"Ilmu Sejarah (S1)",
		"Administrasi Perpajakan (D3)",
		"Manajemen (S1)",
		"Kesehatan Masyarakat (S1)",
		"Farmasi (S1)",
		"Ilmu Komputer (S1)",
		"Arsitektur Interior (S1)",
		"Matematika (S1)",
		"Administrasi Perkantoran (D3)",
		"Teknik Industri (S1)",
		"Sastra Perancis (S1)",
		"Sastra Jawa (S1)",
		"Ilmu Keperawatan (S1)",
		"Teknik Biomedik (S1)",
		"Kriminologi (S1)",
		"Ilmu Administrasi Niaga (S1)",
		"Administrasi Asuransi & Aktuaria (D3)",
		"Teknik Lingkungan (S1)",
		"Statistika (S1)",
		"Ilmu Hubungan Internasional (S1)",
		"Teknik Metalurgi dan Material (S1)",
		"Teknik Mesin (S1)",
		"Teknik Perkapalan (S1)",
		"Manajemen Rekod dan Arsip (D4)",
		"Geofisika (S1)",
		"Administrasi Rumah Sakit (D3)",
		"Teknik Bioproses (S1)",
		"Antropologi Sosial (S1)",
		"Manajemen Bisnis Pariwisata (D4)",
		"Ilmu Politik (S1)",
		"Sastra Rusia (S1)",
		"Sistem Informasi (S1)",
		"Fisika (S1)",
		"Periklanan Kreatif (D3)",
		"Hubungan Masyarakat (D3)",
		"Geologi (S1)",
		"Sastra Cina (S1)",
		"Teknologi Bioproses (S1)",
		"Sastra Jepang (S1)",
		"Sastra Belanda (S1)",
		"Bisnis Kreatif (D4)",
		"Produksi Media (D4)",
		"Kesehatan Lingkungan (S1)",
		"Ilmu Administrasi Fiskal (S1)",
		"Sastra Jerman (S1)",
		"Teknik Kimia (S1)",
		"Fisioterapi (D4)",
		"Penyiaran Multimedia (D3)",
		"Ilmu Ekonomi (S1)",
		"Sastra Arab (S1)",
		"Bisnis Islam (S1)",
		"Arsitektur (S1)",
		"Sosiologi (S1)",
		"Pendidikan Dokter (S1)",
		"Ilmu Aktuaria (S1)",
		"Sastra Inggris (S1)",
		"Sastra Indonesia (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Bahasa Dan Kebudayaan Korea (S1)",
		"Psikologi (S1)",
		"Ilmu Perpustakaan (S1)",
		"Ekonomi Islam (S1)"
	  ]
	},
	{
	  "nama": "Universitas Jember",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Teknik Pertanian (S1)",
		"Ilmu Hubungan Internasional (S1)",
		"Biologi (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Televisi Dan Film (S1)",
		"Pendidikan Ekonomi (S1)",
		"Teknik Mesin (S1)",
		"Informatika (S1)",
		"Ilmu Kesejahteraan Sosial (S1)",
		"Pendidikan Dokter Gigi (S1)",
		"Pendidikan Sejarah (S1)",
		"Peternakan (S1)",
		"Ilmu Sejarah (S1)",
		"Akuntansi (S1)",
		"Pendidikan Fisika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Kesekretariatan (D3)",
		"Ilmu Tanah (S1)",
		"Manajemen (S1)",
		"Kesehatan Masyarakat (S1)",
		"Pendidikan Luar Sekolah (S1)",
		"Teknologi Hasil Pertanian (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Pendidikan IPA (S1)",
		"Perencanaan Wilayah dan Kota (S1)",
		"Sistem Informasi (S1)",
		"Agronomi (S1)",
		"Farmasi (S1)",
		"Teknik Elektro (S1)",
		"Teknik Kimia (S1)",
		"Teknik Perminyakan (S1)",
		"Fisika (S1)",
		"Ilmu Pertanian (S1)",
		"Matematika (S1)",
		"Proteksi Tanaman (S1)",
		"Teknik Pertambangan (S1)",
		"Teknologi Informasi (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Teknologi Rekayasa Elektronika (D4)",
		"Ilmu Keperawatan (S1)",
		"Rekayasa Perancangan Mekanik (D4)",
		"Ekonomi Syariah (S1)",
		"Penyuluhan Pertanian (S1)",
		"Pendidikan Matematika (S1)",
		"Sosiologi (S1)",
		"Pendidikan Dokter (S1)",
		"Agroteknologi (S1)",
		"Sastra Inggris (S1)",
		"Teknik Konstruksi Perkapalan (S1)",
		"Administrasi Keuangan (D3)",
		"Keperawatan (Kampus Kota Pasuruan) (D3)",
		"Teknologi Industri Pertanian (S1)",
		"Pendidikan Geografi (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Agribisnis (S1)",
		"Perpajakan (D3)",
		"Sastra Indonesia (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Ilmu Administrasi Niaga (S1)",
		"Pendidikan Biologi (S1)",
		"Kimia (S1)",
		"Teknologi Rekayasa Konstruksi Bangunan Gedung (D4)",
		"Manajemen Perusahaan (D3)",
		"Usaha Perjalanan Wisata (D3)",
		"Keperawatan (D3)"
	  ]
	},
	{
	  "nama": "Universitas Jenderal Soedirman",
	  "namaProdi": [
		"Bisnis Internasional (D3)",
		"Statistika (S1)",
		"Manajemen Sumber Daya Perairan (S1)",
		"Biologi (S1)",
		"Teknik Pertanian (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Pendidikan Bahasa dan Sastra Indonesia (S1)",
		"Pendidikan Ekonomi (S1)",
		"Bahasa Inggris (D3)",
		"Teknik Geologi (S1)",
		"Pendidikan Jasmani (S1)",
		"Teknik Mesin (S1)",
		"Kedokteran Gigi (S1)",
		"Informatika (S1)",
		"Peternakan (S1)",
		"Pendidikan Dokter Gigi (S1)",
		"Akuntansi (S1)",
		"Teknik Informatika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Kesekretariatan (D3)",
		"Pendidikan Bahasa Jepang (S1)",
		"Budi Daya Ternak (D3)",
		"Hukum (S1)",
		"Mikrobiologi (S1)",
		"Manajemen (S1)",
		"Administrasi Publik (S1)",
		"Ilmu Gizi (S1)",
		"Ilmu Politik (S1)",
		"Kesehatan Masyarakat (S1)",
		"Perencanaan Sumber Daya Lahan (D3)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Bahasa Mandarin (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Keperawatan (S1)",
		"Produksi Ternak (D3)",
		"Teknik Elektro (S1)",
		"Farmasi (S1)",
		"Fisika (S1)",
		"Matematika (S1)",
		"Administrasi Perkantoran (D3)",
		"Proteksi Tanaman (S1)",
		"Teknik Industri (S1)",
		"Ilmu Komunikasi (S1)",
		"Biologi (D3)",
		"Agrobisnis (D3)",
		"Kedokteran (S1)",
		"Ilmu Keperawatan (S1)",
		"Biologi Terapan (S1)",
		"Sosiologi (S1)",
		"Pendidikan Bahasa Indonesia (S1)",
		"Agroteknologi (S1)",
		"Sastra Inggris (S1)",
		"Administrasi Bisnis (D3)",
		"Administrasi Keuangan (D3)",
		"Teknik Komputer (S1)",
		"Hubungan Internasional (S1)",
		"Budidaya Perairan (S1)",
		"Teknologi Pangan (S1)",
		"Agribisnis (S1)",
		"Sastra Indonesia (S1)",
		"Pendidikan Jasmani Kesehatan dan Rekreasi (S1)",
		"Teknik Sipil (S1)",
		"Sastra Jepang (S1)",
		"Agribisnis (D3)",
		"Budi Daya Ikan (D3)",
		"Kimia (S1)",
		"Ilmu Kelautan (S1)",
		"Akuakultur (S1)",
		"Ilmu dan Teknologi Pangan (S1)"
	  ]
	},
	{
	  "nama": "Universitas Negeri Jakarta",
	  "namaProdi": [
		"Biologi (S1)",
		"Ilmu Agama Islam (S1)",
		"Kepelatihan Kecabangan Olahraga (S1)",
		"Pendidikan Bahasa Jerman (S1)",
		"Akuntansi (S1)",
		"Tata Boga (D3)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Usaha Jasa Pariwisata (D3)",
		"Bisnis Digital (S1)",
		"Perpustakaan dan Sains Informasi (S1)",
		"Pendidikan Bisnis (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Keolahragaan (S1)",
		"Geografi (S1)",
		"Pendidikan Tari (S1)",
		"Olahraga Rekreasi (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Kimia (S1)",
		"Bahasa Arab (D3)",
		"Kimia (S1)",
		"Pendidikan Kesejahteraan Keluarga (S1)",
		"Pendidikan Tata Boga (S1)",
		"Administrasi Perkantoran Digital (D4)",
		"Desain Mode (D4)",
		"Pendidikan Teknik Informatika dan Komputer (S1)",
		"Pendidikan Fisika (S1)",
		"Pendidikan Tata Rias (S1)",
		"Manajemen (S1)",
		"Sistem dan Teknologi Informasi (S1)",
		"Pendidikan Tata Busana (S1)",
		"Ilmu Komputer (S1)",
		"Sistem Komputer (S1)",
		"Matematika (S1)",
		"Administrasi Perkantoran (D3)",
		"Tata Rias (D3)",
		"Pendidikan Administrasi Perkantoran (S1)",
		"Rekayasa Keselamatan Kebakaran (S1)",
		"Pendidikan Geografi (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Akuntansi Sektor Publik (D4)",
		"Teknologi Rekayasa Otomasi (D4)",
		"Statistika (S1)",
		"Pendidikan Ekonomi (S1)",
		"Teknik Mesin (S1)",
		"Pendidikan Sejarah (S1)",
		"Pendidikan Bahasa Perancis (S1)",
		"Pendidikan Bahasa Jepang (S1)",
		"Transportasi (D3)",
		"Pendidikan Luar Sekolah (S1)",
		"Teknik Elektronika (D3)",
		"Pendidikan Akuntansi (S1)",
		"Fisika (S1)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Pendidikan Jasmani, Kesehatan & Rekreasi (S1)",
		"Hubungan Masyarakat (D3)",
		"Pendidikan Agama Islam (S1)",
		"Manajemen Pelabuhan dan Logistik Maritim (D4)",
		"Kosmetik dan Perawatan Kecantikan (D4)",
		"Bimbingan Dan Konseling (S1)",
		"Pendidikan Seni Drama, Tari Dan Musik (S1)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Pendidikan Luar Biasa (S1)",
		"Teknologi Rekayasa Konstruksi Bangunan Gedung (D4)",
		"Pendidikan Teknik Mesin (S1)",
		"Usaha Perjalanan Wisata (D4)",
		"Pendidikan Bahasa Inggris (S1)",
		"Sekretari (D3)",
		"Tata Busana (D3)",
		"Teknik Sipil (D3)",
		"Perjalanan Wisata (D3)",
		"Pendidikan Calon Pendidik Akademi Komunitas (S1)",
		"Pendidikan Sosiologi (S1)",
		"Pendidikan Musik (S1)",
		"Seni Kuliner dan Pengelolaan Jasa Makanan (D4)",
		"Pendidikan Teknik Bangunan (S1)",
		"Teknik Mesin (D3)",
		"Manajemen Pemasaran (D3)",
		"Pendidikan Tata Niaga (S1)",
		"Pendidikan Bahasa Mandarin (S1)",
		"Pendidikan Seni Rupa (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Pendidikan Bahasa Arab (S1)",
		"Sosiologi (S1)",
		"Sastra Inggris (S1)",
		"Hubungan Masyarakat Dan Komunikasi Digital (D4)",
		"Pemasaran Digital (D4)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Manajemen Pendidikan (S1)",
		"Sastra Indonesia (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Pendidikan Teknik Elektronika (S1)",
		"Pendidikan IPS (S1)"
	  ]
	},
	{
	  "nama": "Universitas Negeri Malang",
	  "namaProdi": [
		"Biologi (S1)",
		"Pendidikan Bahasa Jerman (S1)",
		"Akuntansi (S1)",
		"Teknik Elektro (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Keolahragaan (S1)",
		"Teknologi Rekayasa Dan Pemeliharaan Bangunan Sipil (D4)",
		"Perpustakaan Digital (D4)",
		"Geografi (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Kimia (S1)",
		"Kimia (S1)",
		"Pendidikan Seni Tari dan Musik (S1)",
		"Pendidikan Tata Boga (S1)",
		"Bioteknologi (S1)",
		"Desain Mode (D4)",
		"Ilmu Sejarah (S1)",
		"Pendidikan Fisika (S1)",
		"Bahasa dan Sastra Indonesia (S1)",
		"Ekonomi Pembangunan (S1)",
		"Pariwisata (S1)",
		"Manajemen (S1)",
		"Desain Komunikasi Visual (S1)",
		"Pendidikan Tata Busana (S1)",
		"Matematika (S1)",
		"Teknik Industri (S1)",
		"Ilmu Kesehatan Masyarakat (S1)",
		"Pendidikan Administrasi Perkantoran (S1)",
		"Pendidikan Jasmani, Kesehatan Dan Rekreasi (S1)",
		"Tata Boga (D4)",
		"Pendidikan Geografi (S1)",
		"Teknik Lingkungan (S1)",
		"Pendidikan Ekonomi (S1)",
		"Teknik Mesin (S1)",
		"Sains Aktuaria (S1)",
		"Pendidikan Bahasa, Sastra Indonesia dan Daerah (S1)",
		"Pendidikan Sejarah (S1)",
		"Administrasi Pendidikan (S1)",
		"Teknologi Rekayasa Otomotif (D4)",
		"Hukum (S1)",
		"Pendidikan Luar Sekolah (S1)",
		"Pendidikan Akuntansi (S1)",
		"Fisika (S1)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Kedokteran (S1)",
		"Pendidikan Teknik Otomotif (S1)",
		"Bimbingan Dan Konseling (S1)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Pendidikan Luar Biasa (S1)",
		"Pendidikan Teknik Mesin (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Pendidikan Teknik Informatika (S1)",
		"Pendidikan Sosiologi (S1)",
		"Teknik Informatika (S1)",
		"Pendidikan Teknik Bangunan (S1)",
		"Pendidikan IPA (S1)",
		"Keperawatan (S1)",
		"Teknologi Rekayasa Pembangkit Energi (D4)",
		"Pendidikan Tata Niaga (S1)",
		"Akuntansi (D4)",
		"Pendidikan Bahasa Mandarin (S1)",
		"Pendidikan Seni Rupa (S1)",
		"Manajemen Pemasaran (D4)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Arsitektur (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Pendidikan Bahasa Arab (S1)",
		"Teknologi Rekayasa Sistem Elektronika (D4)",
		"Bahasa dan Sastra Inggris (S1)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Ilmu Perpustakaan (S1)",
		"Kebidanan (S1)",
		"Pendidikan IPS (S1)",
		"Animasi (D4)"
	  ]
	},
	{
	  "nama": "Universitas Negeri Semarang",
	  "namaProdi": [
		"Biologi (S1)",
		"Pendidikan Bahasa dan Sastra Jawa (S1)",
		"Statistika Terapan dan Komputasi (D3)",
		"Akuntansi (S1)",
		"Ilmu Hukum (S1)",
		"Teknik Elektro (S1)",
		"Desain Komunikasi Visual (D3)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Keolahragaan (S1)",
		"Teknik Komputer (S1)",
		"Geografi (S1)",
		"Pendidikan Ipa (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Kimia (S1)",
		"Kimia (S1)",
		"Pendidikan Kesejahteraan Keluarga (S1)",
		"Pendidikan Tata Boga (S1)",
		"Ilmu Lingkungan (S1)",
		"Pendidikan Teknik Informatika dan Komputer (S1)",
		"Ilmu Sejarah (S1)",
		"Pendidikan Fisika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Manajemen (S1)",
		"Kesehatan Masyarakat (S1)",
		"Farmasi (S1)",
		"Pendidikan Tata Busana (S1)",
		"Matematika (S1)",
		"Seni Rupa (S1)",
		"Sastra Perancis (S1)",
		"Pendidikan Administrasi Perkantoran (S1)",
		"Sastra Jawa (S1)",
		"Pendidikan Ilmu Pengetahuan Sosial (S1)",
		"Pendidikan Geografi (S1)",
		"Bimbingan dan Konseling (S1)",
		"Pendidikan Bahasa dan Sastra Indonesia (S1)",
		"Pendidikan Ekonomi (S1)",
		"Pendidikan Sosiologi Dan Antropologi (S1)",
		"Teknik Mesin (S1)",
		"Pendidikan Sejarah (S1)",
		"Pendidikan Bahasa Perancis (S1)",
		"Pendidikan Bahasa Jepang (S1)",
		"Pendidikan Luar Sekolah (S1)",
		"Ilmu Politik (S1)",
		"Sistem Informasi (S1)",
		"Pendidikan Akuntansi (S1)",
		"Fisika (S1)",
		"Pendidikan Jasmani, Kesehatan & Rekreasi (S1)",
		"Kedokteran (S1)",
		"Pendidikan Non Formal (S1)",
		"Pendidikan Teknik Otomotif (S1)",
		"Pendidikan Seni Drama, Tari Dan Musik (S1)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Ekonomi dan Keuangan Islam (S1)",
		"Pendidikan Teknik Mesin (S1)",
		"Pendidikan Jasmani Sekolah Dasar (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Statistika dan Sains Data (S1)",
		"Pendidikan Bahasa, Sastra Ind Dan Daerah (S1)",
		"Teknik Informatika (S1)",
		"Pendidikan Teknik Bangunan (S1)",
		"Teknik Kimia (S1)",
		"Pendidikan Bahasa Mandarin (S1)",
		"Pendidikan Seni Rupa (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Pendidikan Bahasa Arab (S1)",
		"Sastra Inggris (S1)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Pendidikan Tata Kecantikan (S1)",
		"Sastra Indonesia (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Teknik Arsitektur (S1)"
	  ]
	},
	{
	  "nama": "Universitas Negeri Surabaya",
	  "namaProdi": [
		"Biologi (S1)",
		"Teknik Mesin (D4)",
		"Pendidikan Bahasa Jerman (S1)",
		"Akuntansi (S1)",
		"Sastra Inggris (Kampus Kabupaten Magetan) (S1)",
		"Seni Musik (S1)",
		"Desain Grafis (D4)",
		"Ilmu Hukum (S1)",
		"Ilmu Administrasi Negara (S1)",
		"Perencanaan Wilayah dan Kota (S1)",
		"Teknik Elektro (S1)",
		"Administrasi Negara (D4)",
		"Bisnis Digital (S1)",
		"Pendidikan Bisnis (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Keolahragaan (S1)",
		"Teknik Sipil (D4)",
		"Pendidikan Bahasa Dan Sastra Jawa (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Manajemen Olahraga (S1)",
		"Pendidikan Kimia (S1)",
		"Kimia (S1)",
		"Analisis Performa Olahraga (D4)",
		"Teknik Listrik (D4)",
		"Musik (S1)",
		"Teknologi Pangan dan Hasil Pertanian (S1)",
		"Pendidikan Tata Boga (S1)",
		"Pendidikan Sains (S1)",
		"Pendidikan Fisika (S1)",
		"Pendidikan Tata Rias (S1)",
		"Pariwisata (S1)",
		"Manajemen (S1)",
		"Desain Komunikasi Visual (S1)",
		"Pendidikan Tata Busana (S1)",
		"Fisioterapi (S1)",
		"Sains Data (S1)",
		"Matematika (S1)",
		"Pendidikan Administrasi Perkantoran (S1)",
		"Pendidikan Guru Sekolah Dasar (Kampus Kabupaten Magetan) (S1)",
		"Ilmu Hukum (Kampus Kabupaten Magetan) (S1)",
		"Informatika (Kampus Kabupaten Magetan) (S1)",
		"Tata Boga (D4)",
		"Pendidikan Teknologi Informasi (S1)",
		"Ilmu Komunikasi (Kampus Kabupaten Magetan) (S1)",
		"Pendidikan Geografi (S1)",
		"Pendidikan Ilmu Pengetahuan Alam (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Masase (S1)",
		"Pendidikan Ekonomi (S1)",
		"Pendidikan Jasmani, Kesehatan, dan Rekreasi (Kampus Kabupaten Magetan) (S1)",
		"Teknik Mesin (S1)",
		"Sains Aktuaria (S1)",
		"Tata Busana (D4)",
		"Pendidikan Matematika (Kampus Kabupaten Magetan) (S1)",
		"Pendidikan Sejarah (S1)",
		"Teknologi Rekayasa Otomotif (D4)",
		"Pendidikan Bahasa Jepang (S1)",
		"Pendidikan Luar Sekolah (S1)",
		"Ilmu Politik (S1)",
		"Sistem Informasi (S1)",
		"Kepelatihan Olahraga (D4)",
		"Pendidikan Akuntansi (S1)",
		"Fisika (S1)",
		"Kedokteran (S1)",
		"Manajemen Informatika (D4)",
		"Bimbingan Dan Konseling (S1)",
		"Agribisnis Digital (S1)",
		"Ekonomi (S1)",
		"Hubungan Internasional (S1)",
		"Pendidikan Seni Drama, Tari Dan Musik (S1)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Kecerdasan Artifisial (S1)",
		"Transportasi (D4)",
		"Film dan Animasi (S1)",
		"Pendidikan Luar Biasa (S1)",
		"Pendidikan Teknik Mesin (S1)",
		"Akuakultur (S1)",
		"Manajemen (Kampus Kabupaten Magetan) (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Teknik Informatika (S1)",
		"Seni Rupa Murni (S1)",
		"Pendidikan Teknik Bangunan (S1)",
		"Sastra Jerman (S1)",
		"Keperawatan (S1)",
		"Biosains Hewan (S1)",
		"Pendidikan Tata Niaga (S1)",
		"Pendidikan Bahasa Mandarin (S1)",
		"Pendidikan Seni Rupa (S1)",
		"Pendidikan Jasmani, Kesehatan, dan Rekreasi (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Sosiologi (S1)",
		"Sastra Inggris (S1)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Manajemen Pendidikan (S1)",
		"Sastra Indonesia (S1)",
		"Gizi (S1)",
		"Teknik Sipil (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Pendidikan Tata Rias (Kampus Kabupaten Magetan) (S1)",
		"Kebidanan (S1)",
		"Ekonomi Islam (S1)",
		"Pendidikan IPS (S1)"
	  ]
	},
	{
	  "nama": "Universitas Negeri Yogyakarta",
	  "namaProdi": [
		"Pendidikan Seni Tari (S1)",
		"Biologi (S1)",
		"Teknik Mesin (D4)",
		"Pendidikan Bahasa Jerman (S1)",
		"Akuntansi (S1)",
		"Pendidikan Seni Musik (S1)",
		"Administrasi Publik (S1)",
		"Ilmu Hukum (S1)",
		"Teknik Elektro (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Keolahragaan (S1)",
		"Teknik Sipil (D4)",
		"Teknik Elektro (D4)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Kimia (S1)",
		"Kimia (S1)",
		"Pendidikan Tata Boga (S1)",
		"Ilmu Sejarah (S1)",
		"Pendidikan Fisika (S1)",
		"Pariwisata (S1)",
		"Manajemen (S1)",
		"Kebijakan Pendidikan (S1)",
		"Pendidikan Tata Busana (S1)",
		"Matematika (S1)",
		"Teknik Industri (S1)",
		"Pendidikan Administrasi Perkantoran (S1)",
		"Pendidikan Jasmani, Kesehatan Dan Rekreasi (S1)",
		"Pendidikan Ilmu Pengetahuan Sosial (S1)",
		"Pendidikan Kriya (S1)",
		"Tata Boga (D4)",
		"Pendidikan Geografi (S1)",
		"Pendidikan Ilmu Pengetahuan Alam (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Pendidikan Teknik Mekatronika (S1)",
		"Statistika (S1)",
		"Pendidikan Ekonomi (S1)",
		"Tata Busana (D4)",
		"Pendidikan Sejarah (S1)",
		"Administrasi Pendidikan (S1)",
		"Pendidikan Bahasa Perancis (S1)",
		"Mesin Otomotif (D4)",
		"Pendidikan Luar Sekolah (S1)",
		"Ilmu Politik (S1)",
		"Pendidikan Akuntansi (S1)",
		"Fisika (S1)",
		"Kedokteran (S1)",
		"Teknik Manufaktur (S1)",
		"Pendidikan Teknik Otomotif (S1)",
		"Bimbingan Dan Konseling (S1)",
		"Promosi Kesehatan (D4)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Pendidikan Bahasa Jawa (S1)",
		"Pendidikan Luar Biasa (S1)",
		"Pendidikan Teknik Mesin (S1)",
		"Pendidikan Jasmani Sekolah Dasar (S1)",
		"Pendidikan Teknik Sipil dan Perencanaan (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Pendidikan Teknik Informatika (S1)",
		"Pengobatan Tradisional (D4)",
		"Pendidikan Calon Pendidik Akademi Komunitas (S1)",
		"Pendidikan Sosiologi (S1)",
		"PGSD Pendidikan Jasmani (S1)",
		"Akuntansi (D4)",
		"Pendidikan Seni Rupa (S1)",
		"Teknologi Informasi (S1)",
		"Manajemen Pemasaran (D4)",
		"Teknik Elektronika (D4)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Arsitektur (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Sastra Inggris (S1)",
		"Pengelolaan Usaha Rekreasi (D4)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Manajemen Pendidikan (S1)",
		"Sastra Indonesia (S1)",
		"Tata Rias dan Kecantikan (D4)",
		"Teknik Sipil (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Pendidikan Teknik Elektronika (S1)",
		"Administrasi Perkantoran (D4)"
	  ]
	},
	{
	  "nama": "Universitas Padjadjaran",
	  "namaProdi": [
		"Bisnis Internasional (D4)",
		"Statistika (S1)",
		"Ilmu Hubungan Internasional (S1)",
		"Biologi (S1)",
		"Administrasi Pemerintahan (D4)",
		"Manajemen Produksi Media (D4)",
		"Sastra Sunda (S1)",
		"Teknik Pertanian (S1)",
		"Televisi dan Film (S1)",
		"Teknik Geologi (S1)",
		"Antropologi (S1)",
		"Ilmu Kesejahteraan Sosial (S1)",
		"Akuntansi Perpajakan (D4)",
		"Pendidikan Dokter Gigi (S1)",
		"Peternakan (S1)",
		"Geofisika (S1)",
		"Ilmu Sejarah (S1)",
		"Akuntansi (S1)",
		"Ilmu Pemerintahan (S1)",
		"Teknik Informatika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Manajemen (S1)",
		"Administrasi Publik (S1)",
		"Ilmu Politik (S1)",
		"Peternakan K. Pangandaran (S1)",
		"Sastra Jerman (S1)",
		"Ilmu Hukum (S1)",
		"Pariwisata Bahari (D4)",
		"Sastra Rusia (S1)",
		"Teknik Elektro (S1)",
		"Bisnis Digital (S1)",
		"Farmasi (S1)",
		"Agroteknopreneur (D4)",
		"Perpustakaan dan Sains Informasi (S1)",
		"Fisika (S1)",
		"Matematika (S1)",
		"Ilmu Ekonomi (S1)",
		"Administrasi Bisnis K. Pangandaran (S1)",
		"Sastra Arab (S1)",
		"Sastra Perancis (S1)",
		"Ilmu Komunikasi (S1)",
		"Kedokteran (S1)",
		"Manajemen Komunikasi (S1)",
		"Ilmu Keperawatan (S1)",
		"Perikanan Laut Tropis K Pangandaran (S1)",
		"Ilmu Komunikasi K. Pangandaran (S1)",
		"Ilmu Administrasi Bisnis (S1)",
		"Teknologi Industri Kimia (D4)",
		"Perikanan K Pangandaran (S1)",
		"Sosiologi (S1)",
		"Agroteknologi (S1)",
		"Ilmu Aktuaria (S1)",
		"Administrasi Keuangan Publik (D4)",
		"Bahasa dan Budaya Tiongkok (D4)",
		"Perikanan (S1)",
		"Hubungan Internasional (S1)",
		"Kearsipan Digital (D4)",
		"Pemasaran Digital (D4)",
		"Sastra Inggris (S1)",
		"Bisnis Logistik (D4)",
		"Teknologi Industri Pertanian (S1)",
		"Kebidanan (D4)",
		"Agribisnis (S1)",
		"Kedokteran Hewan (S1)",
		"Teknologi Pangan (S1)",
		"Sastra Indonesia (S1)",
		"Akuntansi Sektor Publik (D4)",
		"Sastra Jepang (S1)",
		"Hubungan Masyarakat (S1)",
		"Psikologi (S1)",
		"Ilmu Perpustakaan (S1)",
		"Kimia (S1)",
		"Ekonomi Islam (S1)",
		"Ilmu Kelautan (S1)",
		"Jurnalistik (S1)",
		"Keperawatan K. Pangandaran (S1)"
	  ]
	},
	{
	  "nama": "Universitas Pembangunan Nasional Veteran Jakarta",
	  "namaProdi": [
		"Ilmu Hubungan Internasional (S1)",
		"Hukum Bisnis (S1)",
		"Perbankan dan Keuangan (D3)",
		"Manajemen Informatika (D3)",
		"Teknik Mesin (S1)",
		"Teknik Perkapalan (S1)",
		"Informatika (S1)",
		"Akuntansi (S1)",
		"Kajian Film, Televisi, dan Media (S1)",
		"Sistem Informasi (D3)",
		"Sains Informasi (S1)",
		"Ekonomi Pembangunan (S1)",
		"Teknik Informatika (S1)",
		"Fisioterapi (D3)",
		"Hukum (S1)",
		"Keuangan dan Perbankan (D3)",
		"Kesehatan Masyarakat (S1)",
		"Ilmu Gizi (S1)",
		"Ilmu Politik (S1)",
		"Manajemen (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Keperawatan (S1)",
		"Sistem Informasi (S1)",
		"Teknik Elektro (S1)",
		"Farmasi (S1)",
		"Fisioterapi (S1)",
		"Sains Data (S1)",
		"Teknik Industri (S1)",
		"Ilmu Komunikasi (S1)",
		"Kedokteran (S1)",
		"Ilmu Keperawatan (S1)",
		"Ekonomi Syariah (S1)",
		"Pendidikan Dokter (S1)",
		"Hubungan Internasional (S1)",
		"Gizi (S1)",
		"Keperawatan (D3)"
	  ]
	},
	{
	  "nama": "Universitas Pembangunan Nasional Veteran Jawa Timur",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Teknik Mesin (S1)",
		"Informatika (S1)",
		"Akuntansi (S1)",
		"Teknik Informatika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Linguistik Indonesia (S1)",
		"Pariwisata (S1)",
		"Hukum (S1)",
		"Manajemen (S1)",
		"Administrasi Publik (S1)",
		"Desain Komunikasi Visual (S1)",
		"Ilmu Hukum (S1)",
		"Ilmu Administrasi Negara (S1)",
		"Teknik Kimia (S1)",
		"Sistem Informasi (S1)",
		"Administrasi Bisnis (S1)",
		"Bisnis Digital (S1)",
		"Desain Interior (S1)",
		"Sains Data (S1)",
		"Fisika (S1)",
		"Teknik Industri (S1)",
		"Ilmu Komunikasi (S1)",
		"Kedokteran (S1)",
		"Arsitektur (S1)",
		"Ilmu Administrasi Bisnis (S1)",
		"Agroteknologi (S1)",
		"Hubungan Internasional (S1)",
		"Teknologi Pangan (S1)",
		"Agribisnis (S1)",
		"Teknik Sipil (S1)",
		"Bahasa Inggris Untuk Komunikasi Bisnis Dan Profesional (D4)",
		"Kewirausahaan (S1)"
	  ]
	},
	{
	  "nama": "Universitas Pembangunan Nasional Veteran Yogyakarta",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Ilmu Hubungan Internasional (S1)",
		"Teknik Geologi (S1)",
		"Informatika (S1)",
		"Teknik Metalurgi (S1)",
		"Akuntansi (S1)",
		"Ekonomi Pembangunan (S1)",
		"Ilmu Tanah (S1)",
		"Manajemen (S1)",
		"Teknik Kimia (D3)",
		"Teknik Kimia (S1)",
		"Sistem Informasi (S1)",
		"Teknik Perminyakan (S1)",
		"Teknik Industri (S1)",
		"Teknik Pertambangan (S1)",
		"Teknik Geofisika (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Administrasi Bisnis (S1)",
		"Teknik Geomatika (S1)",
		"Agroteknologi (S1)",
		"Agribisnis (S1)",
		"Hubungan Masyarakat (S1)"
	  ]
	},
	{
	  "nama": "Universitas Pendidikan Indonesia",
	  "namaProdi": [
		"Pendidikan Seni Tari (S1)",
		"Biologi (S1)",
		"Pendidikan Manajemen Perkantoran (S1)",
		"PGSD Kampus Sumedang (S1)",
		"Pendidikan Masyarakat (S1)",
		"Keperawatan Kampus Sumedang (D3)",
		"Pendidikan Bahasa Jerman (S1)",
		"Pendidikan Ilmu Komputer (S1)",
		"Akuntansi (S1)",
		"Pendidikan Seni Musik (S1)",
		"Ilmu Hukum (S1)",
		"Teknik Elektro (S1)",
		"Kepelatihan Fisik Olahraga (S1)",
		"Bisnis Digital (S1)",
		"Perpustakaan dan Sains Informasi (S1)",
		"Industri Pariwisata (S1)",
		"Ilmu Komunikasi (S1)",
		"Pendidikan Bisnis (S1)",
		"Ilmu Keolahragaan (S1)",
		"PGSD Kampus Tasikmalaya (S1)",
		"PGPAUD Kampus Tasikmalaya (S1)",
		"Teknik Komputer (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Kimia (S1)",
		"Sistem Informasi Kelautan (S1)",
		"Kimia (S1)",
		"Teknik Logistik (S1)",
		"Pendidikan Kesejahteraan Keluarga (S1)",
		"Musik (S1)",
		"Pendidikan Tata Boga (S1)",
		"Pendidikan Khusus (S1)",
		"Sistem Telekomunikasi (S1)",
		"Pendidikan Bahasa Sunda (S1)",
		"Pendidikan Fisika (S1)",
		"Bahasa dan Sastra Indonesia (S1)",
		"Keperawatan Kampus Sumedang (S1)",
		"PGSD Kampus Purwakarta (S1)",
		"Manajemen (S1)",
		"Desain Komunikasi Visual (S1)",
		"Logistik Kelautan (S1)",
		"Pendidikan Tata Busana (S1)",
		"Ilmu Komputer (S1)",
		"Ilmu Pendidikan Agama Islam (S1)",
		"Matematika (S1)",
		"Pendidikan Jasmani, Kesehatan Dan Rekreasi (S1)",
		"Pendidikan Sistem dan Teknologi Informasi Kampus Purwakarta (S1)",
		"Kewirausahaan Kampus Tasikmalaya (S1)",
		"Sains Informasi Geografi (S1)",
		"PGSD Penjas Kampus Sumedang (S1)",
		"Manajemen Pemasaran Pariwisata (S1)",
		"Pendidikan Geografi (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Teknologi Pangan (S1)",
		"Pendidikan Kelautan dan Perikanan Kampus Serang (S1)",
		"Ilmu Ekonomi dan Keuangan Islam (S1)",
		"Pendidikan Ekonomi (S1)",
		"PGSD Kampus Serang (S1)",
		"Pendidikan Sejarah (S1)",
		"Administrasi Pendidikan (S1)",
		"Pendidikan Bahasa Perancis (S1)",
		"PGPAUD Kampus Serang (S1)",
		"PGSD Kampus Cibiru (S1)",
		"Pendidikan Bahasa Jepang (S1)",
		"Pendidikan Akuntansi (S1)",
		"Pendidikan Multimedia Kampus Cibiru (S1)",
		"Fisika (S1)",
		"Pendidikan Teknik Arsitektur (S1)",
		"Kedokteran (S1)",
		"Pendidikan Teknik Otomotif (S1)",
		"Pendidikan Teknologi Agroindustri (S1)",
		"Pendidikan Bahasa Korea (S1)",
		"Pendidikan Pariwisata (S1)",
		"Teknik Energi Terbarukan (S1)",
		"Bimbingan Dan Konseling (S1)",
		"Film dan Televisi (S1)",
		"Manajemen Industri Katering (S1)",
		"PGPAUD Kampus Cibiru (S1)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Survei Pemetaan dan Informasi Geografis (D4)",
		"Pendidikan Teknik Mesin (S1)",
		"Keperawatan (D3)",
		"Pendidikan Bahasa Inggris (S1)",
		"Rekayasa Perangkat Lunak (S1)",
		"Pendidikan Sosiologi (S1)",
		"Pendidikan Teknik Otomasi Industri dan Robotika (S1)",
		"Pendidikan Teknik Bangunan (S1)",
		"PGPAUD Kampus Purwakarta (S1)",
		"PGSD Pendidikan Jasmani (S1)",
		"Pendidikan IPA (S1)",
		"Teknik Kimia (S1)",
		"Keperawatan (S1)",
		"Pendidikan Seni Rupa (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Manajemen Resort dan Leisure (S1)",
		"Mekatronika dan Kecerdasan Buatan Kampus Purwakarta (S1)",
		"Arsitektur (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Pendidikan Bahasa Arab (S1)",
		"Bahasa dan Sastra Inggris (S1)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Desain Produk Industri Kampus Tasikmalaya (S1)",
		"Pendidikan IPS (S1)",
		"Survey Pemetaan dan Informasi Geografis (D3)"
	  ]
	},
	{
	  "nama": "Universitas Sebelas Maret",
	  "namaProdi": [
		"Farmasi (D3)",
		"Biologi (S1)",
		"Informatika PSDKU (Kampus Kabupaten Kebumen) (S1)",
		"Bahasa Inggris (D3)",
		"Informatika (S1)",
		"Manajemen Pemasaran (Kampus Kab. Magetan) (D3)",
		"Peternakan (S1)",
		"Akuntansi (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Bahasa Mandarin (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Komunikasi Terapan (D3)",
		"Teknik Elektro (S1)",
		"Desain Komunikasi Visual (D3)",
		"Bisnis Digital (S1)",
		"Perencanaan Wilayah Dan Kota (S1)",
		"Ilmu Komunikasi (S1)",
		"Keperawatan Anestesiologi (D4)",
		"Agroteknologi (S1)",
		"Kriya Seni (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Teknologi Hasil Pertanian (D3)",
		"Pendidikan Kimia (S1)",
		"Keselamatan Dan Kesehatan Kerja (D4)",
		"Agribisnis (D3)",
		"Kimia (S1)",
		"Sastra Daerah (S1)",
		"Perbankan dan Keuangan Digital (D4)",
		"Demografi dan Pencatatan Sipil (D4)",
		"Ilmu Lingkungan (S1)",
		"Pendidikan Teknik Informatika & Komputer (S1)",
		"Ilmu Sejarah (S1)",
		"Pendidikan Fisika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Manajemen (S1)",
		"Desain Komunikasi Visual (S1)",
		"Farmasi (S1)",
		"Desain Interior (S1)",
		"Sains Data (S1)",
		"Matematika (S1)",
		"Teknik Industri (S1)",
		"Seni Rupa (S1)",
		"Pendidikan Administrasi Perkantoran (S1)",
		"Pendidikan Jasmani, Kesehatan Dan Rekreasi (S1)",
		"Penyuluhan dan Komunikasi Pertanian (S1)",
		"Pendidikan Geografi (S1)",
		"Ilmu Teknologi Pangan (S1)",
		"Pendidikan Ilmu Pengetahuan Alam (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Agribisnis (S1)",
		"Pendidikan Guru Sekolah Dasar (Kampus Kabupaten Kebumen) (S1)",
		"Teknik Informatika K. Kab. Madiun (D3)",
		"Bahasa Mandarin untuk Komunikasi Bisnis dan Profesional (D4)",
		"Statistika (S1)",
		"Pendidikan Ekonomi (S1)",
		"Teknik Mesin (S1)",
		"Pendidikan Sosiologi Antropologi (S1)",
		"Pendidikan Sejarah (S1)",
		"Teknik Informatika (D3)",
		"Agribisnis (Kampus Kab. Magetan) (D3)",
		"Ilmu Tanah (S1)",
		"Teknik Kimia (D3)",
		"Bahasa Mandarin dan Kebudayaan Tiongkok (S1)",
		"Pendidikan Akuntansi (S1)",
		"Fisika (S1)",
		"Pengelolaan Hutan (S1)",
		"Proteksi Tanaman (S1)",
		"Teknologi Rekayasa Manufaktur (D4)",
		"Kedokteran (S1)",
		"Manajemen Perdagangan (D3)",
		"Bimbingan Dan Konseling (S1)",
		"Hubungan Internasional (S1)",
		"Perpajakan (Kampus Kab. Magetan) (D3)",
		"Kebidanan (D4)",
		"Perpustakaan (D3)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Pendidikan Luar Biasa (S1)",
		"Pendidikan Teknik Mesin (S1)",
		"Keuangan Dan Perbankan (D3)",
		"Manajemen Bisnis (D3)",
		"Pendidikan Bahasa Inggris (S1)",
		"Teknik Sipil (D3)",
		"Pendidikan Calon Pendidik Akademi Komunitas (S1)",
		"Seni Rupa Murni (S1)",
		"Kebidanan (D3)",
		"Akuntansi (Kampus Kab. Madiun) (D3)",
		"Budi Daya Ternak (D3)",
		"Manajemen Administrasi (D3)",
		"Pendidikan Teknik Bangunan (S1)",
		"Teknik Kimia (S1)",
		"Teknik Mesin (D3)",
		"Manajemen Pemasaran (D3)",
		"Pendidikan Seni Rupa (S1)",
		"Sastra Arab (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"PJJ Pendidikan Guru Sekolah Dasar (S1)",
		"Arsitektur (S1)",
		"Teknologi Pendidikan (S1)",
		"Pendidikan Matematika (S1)",
		"Ilmu Administrasi Negara PSDKU (Kampus Kabupaten Kebumen) (S1)",
		"Sosiologi (S1)",
		"Sastra Inggris (S1)",
		"Pemasaran Digital (D4)",
		"Pendidikan Kepelatihan Olahraga (S1)",
		"Perpajakan (D3)",
		"Sastra Indonesia (S1)",
		"Teknik Sipil (S1)",
		"Desain Mode (S1)",
		"Pendidikan Biologi (S1)",
		"Psikologi (S1)",
		"Kebidanan (S1)",
		"Pendidikan Bahasa jawa (S1)",
		"Usaha Perjalanan Wisata (D3)"
	  ]
	},
	{
	  "nama": "Universitas Siliwangi",
	  "namaProdi": [
		"Perbankan dan Keuangan Digital (D4)",
		"Pendidikan Bahasa Inggris (S1)",
		"Teknologi Pangan dan Hasil Pertanian (S1)",
		"Pendidikan Ekonomi (S1)",
		"Pendidikan Masyarakat (S1)",
		"Pendidikan Jasmani (S1)",
		"Informatika (S1)",
		"Pendidikan Sejarah (S1)",
		"Pendidikan Fisika (S1)",
		"Akuntansi (S1)",
		"Ekonomi Pembangunan (S1)",
		"Manajemen (S1)",
		"Kesehatan Masyarakat (S1)",
		"Ilmu Politik (S1)",
		"Teknik Elektro (S1)",
		"Sistem Informasi (S1)",
		"Pendidikan Matematika (S1)",
		"Pendidikan Bahasa Indonesia (S1)",
		"Agroteknologi (S1)",
		"Ekonomi Syari'ah (S1)",
		"Pendidikan Geografi (S1)",
		"Agribisnis (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Pendidikan Biologi (S1)",
		"Manajemen Mutu Halal (S1)",
		"Perbankan dan Keuangan (D3)"
	  ]
	},
	{
	  "nama": "Universitas Singaperbangsa Karawang",
	  "namaProdi": [
		"Teknik Lingkungan (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Pendidikan Masyarakat (S1)",
		"Teknik Mesin (S1)",
		"Pendidikan Jasmani Kesehatan & Rekreasi (S1)",
		"Informatika (S1)",
		"Akuntansi (S1)",
		"Ilmu Pemerintahan (S1)",
		"Teknik Informatika (S1)",
		"Kebidanan (D3)",
		"Manajemen (S1)",
		"Pendidikan Luar Sekolah (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Teknik Kimia (S1)",
		"Teknik Mesin (D3)",
		"Teknik Elektro (S1)",
		"Sistem Informasi (S1)",
		"Farmasi (S1)",
		"Fisika (S1)",
		"Teknik Industri (S1)",
		"Ilmu Komunikasi (S1)",
		"Ilmu Keolahragaan (S1)",
		"Pendidikan Agama Islam (S1)",
		"Pendidikan Matematika (S1)",
		"Agroteknologi (S1)",
		"Pendidikan Islam Anak Usia Dini (S1)",
		"Hubungan Internasional (S1)",
		"Manajemen Pendidikan Islam (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Agribisnis (S1)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Administrasi Rumah Sakit (S1)"
	  ]
	},
	{
	  "nama": "Universitas Sultan Ageng Tirtayasa",
	  "namaProdi": [
		"Statistika (S1)",
		"Pendidikan Seni, Drama, Tari, dan Musik (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Perbankan dan Keuangan (D3)",
		"Teknik Mesin (S1)",
		"Pendidikan Khusus (S1)",
		"Administrasi Pajak (D3)",
		"Informatika (S1)",
		"Pendidikan Sejarah (S1)",
		"Peternakan (S1)",
		"Pendidikan Fisika (S1)",
		"Ilmu Pemerintahan (S1)",
		"Akuntansi (S1)",
		"Pendidikan Sosiologi (S1)",
		"Teknik Metalurgi (S1)",
		"Ekonomi Pembangunan (S1)",
		"Agroekoteknologi (S1)",
		"Hukum (S1)",
		"Manajemen (S1)",
		"Administrasi Publik (S1)",
		"Pendidikan Luar Sekolah (S1)",
		"Pendidikan Vokasional Teknik Elektro (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Ilmu Perikanan (S1)",
		"Keperawatan (S1)",
		"Teknik Elektro (S1)",
		"Manajemen Pemasaran (D3)",
		"Pendidikan Seni Pertunjukan (S1)",
		"Teknik Kimia (S1)",
		"Teknik Industri (S1)",
		"Pendidikan Pancasila dan Kewarganegaraan (S1)",
		"Ilmu Komunikasi (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Ilmu Keolahragaan (S1)",
		"Kedokteran (S1)",
		"Pendidikan Non Formal (S1)",
		"Ekonomi Syariah (S1)",
		"Pendidikan Matematika (S1)",
		"Marketing (D3)",
		"Pendidikan Bahasa Indonesia (S1)",
		"Bimbingan Dan Konseling (S1)",
		"Bimbingan Konseling (S1)",
		"Perikanan (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Ilmu Pengetahuan Alam (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Teknologi Pangan (S1)",
		"Agribisnis (S1)",
		"Pendidikan Kimia (S1)",
		"Pendidikan Vokasional Teknik Mesin (S1)",
		"Perpajakan (D3)",
		"Gizi (S1)",
		"Teknik Sipil (S1)",
		"Pendidikan Teknik Elektro (S1)",
		"Pendidikan Biologi (S1)",
		"Ekonomi Islam (S1)",
		"Pendidikan Luar Biasa (S1)",
		"Ilmu Kelautan (S1)",
		"Pendidikan Teknik Mesin (S1)",
		"Keuangan Dan Perbankan (D3)",
		"Keperawatan (D3)"
	  ]
	},
	{
	  "nama": "Universitas Terbuka",
	  "namaProdi": [
		"Statistika (S1)",
		"Biologi (S1)",
		"Pendidikan Bahasa Inggris (S1)",
		"Pendidikan Ekonomi (S1)",
		"Pendidikan Fisika (S1)",
		"Akuntansi (S1)",
		"Ilmu Pemerintahan (S1)",
		"Ekonomi Pembangunan (S1)",
		"Kearsipan (D4)",
		"Manajemen (S1)",
		"Ilmu Hukum (S1)",
		"Ilmu Administrasi Negara (S1)",
		"Sistem Informasi (S1)",
		"Sains Data (S1)",
		"Akuntansi Keuangan Publik (S1)",
		"Matematika (S1)",
		"Perencanaan Wilayah Dan Kota (S1)",
		"Ilmu Komunikasi (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Pendidikan Agama Islam (S1)",
		"Teknologi Pendidikan (S1)",
		"Ekonomi Syariah (S1)",
		"Ilmu Administrasi Bisnis (S1)",
		"Pendidikan Matematika (S1)",
		"Sosiologi (S1)",
		"Sastra Inggris (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Teknologi Pangan (S1)",
		"Agribisnis (S1)",
		"Pendidikan Kimia (S1)",
		"Perpajakan (D3)",
		"Perpajakan (S1)",
		"PJJ Pariwisata (S1)",
		"Pendidikan Biologi (S1)",
		"Pendidikan Pancasila Dan Kewarganegaraan (S1)",
		"Ilmu Perpustakaan (S1)"
	  ]
	},
	{
	  "nama": "Universitas Tidar",
	  "namaProdi": [
		"Farmasi (D3)",
		"Pendidikan Bahasa Inggris (S1)",
		"Teknik Mesin (S1)",
		"Peternakan (S1)",
		"Akuntansi Perpajakan (D4)",
		"Akuntansi (S1)",
		"Ekonomi Pembangunan (S1)",
		"Pariwisata (S1)",
		"Hukum (S1)",
		"Manajemen (S1)",
		"Pendidikan IPA (S1)",
		"Akuntansi (D3)",
		"Ilmu Administrasi Negara (S1)",
		"Teknik Mekatronika (S1)",
		"Teknik Elektro (S1)",
		"Teknik Mesin (D3)",
		"Teknologi Informasi (S1)",
		"Teknik Industri (S1)",
		"Ilmu Komunikasi (S1)",
		"Pendidikan Matematika (S1)",
		"Agroteknologi (S1)",
		"Pendidikan Bahasa Dan Sastra Indonesia (S1)",
		"Teknologi Pangan (S1)",
		"Agribisnis (S1)",
		"Teknologi Rekayasa Perancangan Manufaktur (D4)",
		"Teknik Sipil (S1)",
		"Gizi (S1)",
		"Pendidikan Biologi (S1)",
		"Akuakultur (S1)"
	  ]
	},
	{
	  "nama": "Universitas Trunojoyo",
	  "namaProdi": [
		"Pendidikan Bahasa dan Sastra Indonesia (S1)",
		"Teknik Mesin (S1)",
		"Akuntansi (S1)",
		"Teknik Informatika (S1)",
		"Ekonomi Pembangunan (S1)",
		"Agroekoteknologi (S1)",
		"Manajemen (S1)",
		"Ilmu Hukum (S1)",
		"Akuntansi (D3)",
		"Teknik Mekatronika (S1)",
		"Teknik Elektro (S1)",
		"Sistem Informasi (S1)",
		"Teknik Industri (S1)",
		"Hukum Bisnis Syariah (S1)",
		"Ilmu Komunikasi (S1)",
		"Pendidikan Guru Pendidikan Anak Usia Dini (S1)",
		"Ekonomi Syariah (S1)",
		"Sosiologi (S1)",
		"Sastra Inggris (S1)",
		"Teknologi Industri Pertanian (S1)",
		"Pendidikan Guru Sekolah Dasar (S1)",
		"Pendidikan Ilmu Pengetahuan Alam (S1)",
		"Agribisnis (S1)",
		"Enterpreneurship (D3)",
		"Manajemen Sumberdaya Perairan (S1)",
		"Pendidikan Informatika (S1)",
		"Psikologi (S1)",
		"Ilmu Kelautan (S1)"
	  ]
	}
  ]
  